### ISSUE TITLE
nixpkgs-review doesn't detect changed attributes in the versioned ocamlPackages sets

### ISSUE THREAD

**Issue by sternenseemann** [Mic92/nixpkgs-review#151]
I'm not exactly sure why that is, but `nixpkgs-review` doesn't notice changed attributes in the versioned `ocaml-ng.ocamlPackages_*` sets, but only in the main `ocamlPackages` set. This is a bit problematic, since it means that with `nixpkgs-review` it is not possible to see if a package update breaks other packages (or the package itself) for lower OCaml versions which happens quite commonly in the OCaml world. Since `nixpkgs-review` is often used to judge seemingly trivial version bumps, PR reviewers can [merge pull requests oblivious to potentially unwanted breakages](https://github.com/NixOS/nixpkgs/pull/105293#issuecomment-737209895).

I think this is indeed an issue since you need to specifically know that `nixpkgs-review` doesn't build all changed attributes for `ocamlPackages` whereas this works for `pythonPackages` for example. However there is also another issue: Due to the number of OCaml versions in `nixpkgs` we could be looking at almost 10 times the builds.

**Comment by Mic92** [comment]
It only uses packages found by `nix-env`. `ocamlPackages` has `recurseIntoAttrs` so it is detected.

```
ocamlPackages = recurseIntoAttrs ocaml-ng.ocamlPackages;
```

Evaluating all attributes might require a lot of memory, more than even now. I don't think it is feasible to increase memory usage further. What could work is that ofborg evaluates those package sets so that the attached gist file can be re-used by nixpkgs-review.

**Comment by Mic92** [comment]
Like I said, if this is added to ofborg than nixpkgs-review will have it too.
